[profile.default]
src = 'src/contracts'
test = 'src/test'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/solmate/=node_modules/@rari-capital/solmate/',
    '@contracts/=src/contracts/',
    'hardhat/=node_modules/hardhat/',
]


optimizer = true                 # Enable or disable the solc optimizer
optimizer_runs = 200             # The number of optimizer runs
verbosity = 5                   # The verbosity of tests
invariant_runs = 250000           # The number of calls to make in the invariant tests
invariant_depth = 50             # The number of times to run the invariant tests
invariant_call_override = false  # Override calls
invariant_fail_on_revert = false  # Fail the test if the contract reverts

[profile.local]
fuzz_runs = 100

[profile.deep]
fuzz_runs = 500

[profile.super_deep]
fuzz_runs = 50000