[default]
src = 'src/contracts'
test = 'src/test'
out = 'out'
libs = ['lib']
gas_report = ['xMETRIC']
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@rari-capital/solmate/=node_modules/@rari-capital/solmate/',
    '@contracts/=src/contracts/',
    'hardhat/=node_modules/hardhat/',
]
